stages:
    - pages
    - deploy

pages:
    stage: pages
    image: python:3.7.6
    script:
        - pip install -qq -r requirements.txt
        - pip install .
        - pip list
        - ls ./src/gl_pages_forward/rsc
        - ls /usr/local/lib/python3.7/site-packages/gl_pages_forward/
        - create-forward-pages -c ./src/gl_pages_forward/tests/config.yml
    artifacts:
        paths:
        - public

deploy:
  image: docker:18
  services:
  - docker:18-dind
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_TAG --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA --tag $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME
    - docker push $IMAGE_TAG
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  only:
    refs:
      - master
      - development
      - milestone-*
