stages:
    - pre-analysis
    - build
    - test
    - deploy
    - post-analysis
    - publish

python:build:
    artifacts:
        paths:
            - dist
        expire_in: 3 days
    cache: &python-cache
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - ".venv"
    image: gitlab.lrz.de:5005/i4/software/docker-images/python3.9-poetry
    needs: []
    script:
        - poetry build
    stage: build

python:deploy:
    cache: *python-cache
    image: gitlab.lrz.de:5005/i4/software/docker-images/python3.9-poetry
    rules:
    -   if: '$CI_COMMIT_TAG'
    script:
        - poetry config repositories.lrz https://gitlab.lrz.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
        - poetry publish --repository lrz --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
    stage: deploy
    needs:
        - python:build

container:deploy:
  image: docker:18
  services:
  - docker:18-dind
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_NAME:latest || true
    - docker build
        --build-arg=COMMIT=$CI_COMMIT_SHA
        --build-arg=BRANCH=$CI_COMMIT_BRANCH
        --build-arg=COMMIT_SHORT=$CI_COMMIT_SHORT_SHA
        --build-arg=TAG=$CI_COMMIT_TAG
        --tag $IMAGE_NAME:$CI_COMMIT_SHA
        --tag $IMAGE_NAME:latest
        --tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
        --tag $IMAGE_NAME:$CI_COMMIT_REF_NAME
        .
    - docker push $IMAGE_NAME
    - docker push $IMAGE_TAG
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  rules:
      -   if: '$CI_COMMIT_TAG'

pages:
    stage: publish
    image: gitlab.lrz.de:5005/i4/software/docker-images/python3.9-poetry
    script:
        - poetry install
        - poetry run create-forward-pages --config_file ./src/gl_pages_forward/tests/config.yml
    artifacts:
        paths:
        - public
